
-- Vista para sacar todos los jugadores de draft
CREATE OR REPLACE VIEW JUGADORES_DRAFT AS
(

	SELECT J.POSICION, J.NUMDRAFT, J.TIPO , P.*
	FROM JUGADORES J , PERSONAS P
	WHERE J.ID = P.ID 
    and UPPER(TIPO) = 'DRAFT'
    
);


-- Vista para sacar todos los WildCard

CREATE OR REPLACE VIEW JUGADORES_WILDCARD AS
(
    SELECT J.POSICION, J.TIPO , P.*
	FROM JUGADORES J , PERSONAS P
	WHERE J.ID = P.ID 
    and UPPER(TIPO) = 'WILDCARD'
	
);


-- Vista para visualizar los partidos con los nombres de los equipos.
CREATE OR REPLACE VIEW EMPAREJAMIENTOS AS
(

    SELECT P.IDJORNADA AS "JORNADA",P.ID AS "PARTIDO", E.NOMBRE AS "EQUIPO1"
    , EQ.NOMBRE AS "EQUIPO2"
    FROM PARTIDOS P, EQUIPOS E, EQUIPOS EQ
    WHERE P.IDEQUIPO1 = E.ID AND P.IDEQUIPO2 = EQ.ID

);





